stages:
  - build
  - docker

variables:
  TZ: "Europe/Oslo"

build:
  stage: build
  image: circleci/node:10.16-browsers
  script:
    - export BUILD_TIME=$(date '+%Y-%m-%d %H:%M:%S')
    - npm install
    - npm run lint
    - npm run build:prod
  artifacts:
    paths:
      - target/
      - coverage/
    expire_in: 1 week
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

docker-build:
  stage: docker
  dependencies:
    - build
  image: docker:stable
  services:
    - docker:stable-dind
  only:
    - master
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo $CI_RUNNER_TAGS
    - docker info
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
